yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Имя')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Ссылка')
    description = models.TextField(blank=True, null=True,
                                   verbose_name='Описание')

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True, null=True,
        verbose_name='Группа',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField()
    created = models.DateTimeField(
        "date published",
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.title


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following')

    class Meta:
        verbose_name = 'Подписку'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return self.title

yatube/posts/forms.py
from django import forms

from .models import Comment, Follow, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Выберите изображение'
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class FollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = ('user',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import paginator


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related('author', 'group')
    context = {
        'page_obj': paginator(post_list, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
        'page_obj': paginator(post_list, request),
        'is_group': True,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=user
        ).exists()
    else:
        following = False
    context = {
        'author': user,
        'posts': post_list,
        'page_obj': paginator(post_list, request),
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    of_posts = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()

    context = {
        'post': post,
        'of_posts': of_posts,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if request.method == "POST" and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {'form': form,
                                                      'is_edit': True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': paginator(post_list, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = User.objects.get(username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}  
    {% block title %}
      {% if is_edit %}Редактирование поста{% else %}Новый пост{% endif %}      
    {% endblock %}  
  <body>    
    <main>
      {% block content %}    
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}Редактировать запись{% else %}Новый пост{% endif %}             
              </div>
              <div class="card-body">        
                {% include 'posts/includes/error_handling.html' %}
                <form method="post" enctype="multipart/form-data"
                  {% if action_url %}
                  action="{% url action_url %}"
                  {% endif %}
                  >                  
                  {% csrf_token %}
                  {% include 'posts/includes/form.html' %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </main>
  </body>

yatube/templates/posts/follow.html
{% extends 'base.html' %}     
  {% block title %}
  Посты авторов, на которых вы подписаны
  {% endblock %}    
  <body>
    <main>
      {% block content %}
      <div class="container">        
        <h1>Посты авторов, на которых вы подписаны</h1>
        <article>
          {% include 'posts/includes/switcher.html' %}
          {% for post in page_obj %}  
            {% include 'posts/includes/single_post.html' %}            
            <br>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы {{ post.group.title }}
              </a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        </article>        
      </div>
      {% endblock %}
    </main> 
  </body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}    
    {% block title %}
      Записи сообщества {{ group.title }}
    {% endblock %}    
  <body>
    <main>
      {% block content %}
      <div class="container">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        <article>
          {% for post in page_obj %}
            {% include 'posts/includes/single_post.html' %}            
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}        
        </article>        
      </div>
      {% endblock %}  
    </main>
  </body>

yatube/templates/posts/index.html
{% extends 'base.html' %}  
  {% block title %}
    Последние обновления на сайте
  {% endblock %}    
  <body>
    <main>
      {% block content %}
      <div class="container">        
        <h1>Последние обновления сайта</h1>
        <article>
          {% include 'posts/includes/switcher.html' %}          
          {% for post in page_obj %}  
            {% include 'posts/includes/single_post.html' %}            
            <br>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы {{ post.group.title }}
              </a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}          
          {% include 'posts/includes/paginator.html' %}
        </article>        
      </div>
      {% endblock %}
    </main> 
  </body>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
      {% block title %}
        {{ post.text|truncatechars:30 }}
      {% endblock %}      
  <body>    
    <main>
      {% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>              
            {% if post.group %}  
            <li class="list-group-item">
                Группа: {{ post.group.title }}            
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            {% endif %}
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ of_posts }}</span>
              </li>              
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
            {% if request.user == post.author %}
            <li class="list-group-item">
              <a href="{% url 'posts:post_edit' post.id %}">
                Редактировать
              </a>
            {% endif %}  
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>            
          {{ post.text }}
          </p>
          {% include 'posts/includes/comments.html' %}
        </article>
      </div>
      {% endblock %} 
    </main>    
  </body>
 

yatube/templates/posts/profile.html
{% extends 'base.html' %}    
      {% block title %}
        Профайл пользователя {{ author.get_full_name }}
      {% endblock %}    
  <body>       
    <main>
      {% block content %}
      <div class="container py-5">        
        <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ posts|length }} </h3>        
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
        </div>
        <article>
          {% for post in page_obj %}
            {% include 'posts/includes/single_post.html' %}            
            <br>
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group}}</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}          
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}          
        </article>        
      </div>
      {% endblock %}
    </main>
  </body>